### PR TITLE
fix(rules): define an explicit error on non-concurrent index drops

### PR DESCRIPTION
**Pull request by K-Phoen**
Hey!

First of all, really nice and useful project :+1:

While evaluating it to potentially use it at work, I noticed a few slightly misleading violations being reported in some cases. This PR is an attempt at fixing one of them.

```sql
DROP INDEX IF EXISTS some_idx;
```

Would generate a `Create the index CONCURRENTLY.` violation/help message.

To return a more contextually correct message, I introduced a `require-concurrent-index-deletion` that would return `Delete the index CONCURRENTLY.` instead.

In addition to being more accurate, it also gives users more flexibility in terms of what rules are relevant in their context and excludes the ones that aren't.

Let me know if you would accept to review more PRs with similar fix, I'll put my limited rust skills to the task :)

### CODE REVIEW

**Review by chdsbd — APPROVED** [review]
This looks great! Thanks for the contribution. I’m open to similar PRs in the future.

**Comment by sbdchd** [comment]
Hmm why doesn't CI like forks, I don't see the button outlined in https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks to approve and run the actions

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
hmm no dice

**Comment by sbdchd** [comment]
@K-Phoen Can you enable edits from maintainers? I think I need that to get CI to run

**Comment by sbdchd** [comment]
Hmm CI is messed

**Pull request merged**
