### PR TITLE
Build python wheels and upload to pypi

### PR DESCRIPTION
**Pull request by ermakov-oleg**
Hi @chdsbd,

I have started working on issue #261 and have successfully built Python packages for macOS, Windows, and Linux (x86_64).

However, I’m encountering issues building libpg_query-sys for Linux aarch64. Could you please assist me with this?

Thanks!

### CODE REVIEW

**Comment by ermakov-oleg** [comment]
Hi @ods,

I came across your repository where you are already building Python packages: [squawk-cli-python-package](https://github.com/ods/squawk-cli-python-package/tree/master). Thank you for your work on this!

What do you think about moving the build process to this repository, publishing it to your [PyPI squawk-cli](https://pypi.org/project/squawk-cli/), and transferring the rights to @sbdchd and @chdsbd?

**Comment by ods** [comment]
Hi @ermakov-oleg,

> What do you think about moving the build process to this repository, publishing it to your [PyPI squawk-cli](https://pypi.org/project/squawk-cli/), and transferring the rights to @sbdchd and @chdsbd?

It would be the best option!

**Comment by ermakov-oleg** [comment]
> Hi @ermakov-oleg,
> 
> > What do you think about moving the build process to this repository, publishing it to your [PyPI squawk-cli](https://pypi.org/project/squawk-cli/), and transferring the rights to @sbdchd and @chdsbd?
> 
> It would be the best option!

Great!

Now we just need to figure out the build process for the Linux aarch64 package.

**Comment by ermakov-oleg** [comment]
I figured out how to build the package using QEMU, but the build process takes about 30 minutes.

I’m still trying to determine why cross-compilation isn’t working.

@​sbdchd and @​chdsbd, how acceptable would it be to proceed with this longer build time if I’m unable to resolve the cross-compilation issue?

**Comment by ods** [comment]
@ermakov-oleg How do you handle `libpg_query` FFI dependency when cross-compiling?

**Comment by ermakov-oleg** [comment]
> @ermakov-oleg How do you handle `libpg_query` FFI dependency when cross-compiling?

I’m not very experienced in this, but as far as I understand, when selecting a target different from the current system, the entire necessary toolchain for the specific platform is downloaded, and bindgen sets the sysroot path to the header files of that platform from this toolchain

**Comment by ods** [comment]
> I’m not very experienced in this, but as far as I understand, when selecting a target different from the current system, the entire necessary toolchain for the specific platform is downloaded, and bindgen sets the sysroot path to the header files of that platform from this toolchain

I'm neither experienced. What I saw so far, this works perfectly for pure rust code, but not for FFI. Also, I saw maturin docs suggest to [use zig for cross-compilation](https://www.maturin.rs/distribution#use-zig) in such cases.

**Comment by ermakov-oleg** [comment]
> > I’m not very experienced in this, but as far as I understand, when selecting a target different from the current system, the entire necessary toolchain for the specific platform is downloaded, and bindgen sets the sysroot path to the header files of that platform from this toolchain
> 
> I'm neither experienced. What I saw so far, this works perfectly for pure rust code, but not for FFI. Also, I saw maturin docs suggest to [use zig for cross-compilation](https://www.maturin.rs/distribution#use-zig) in such cases.

Thanks for the idea!
The libpg_query-sys library cross-compiles using Zig, but only with glibc version >= 2.38.
I’m currently trying to figure out how to provide Maturin with the appropriate glibc version.

**Comment by ermakov-oleg** [comment]
@sbdchd  I’ve finished building the Python wheels for all major platforms. Could you please review this PR?
Thank you in advance!

**Comment by ermakov-oleg** [comment]
Hi @sbdchd and @chdsbd,

I hope you’re doing well! I just wanted to kindly check in on the status of this pull request. I’ve finished the work on building the Python wheels and would love to hear your thoughts on the feature. Do you think there might be some time in the near future for a code review?

Thank you in advance!

**Comment by sbdchd** [comment]
Is the PR description still accurate, specifically:

> However, I’m encountering issues building libpg_query-sys for Linux aarch64. Could you please assist me with this?


otherwise looks good, thank you for doing this, lot of hard work!!

**Comment by ermakov-oleg** [comment]
Yes, I was able to resolve the issue with the aarch64 build. The package now builds correctly for all major platforms, including Linux aarch64. The description is outdated — everything is working fine now.

**Review by sbdchd — APPROVED** [review]

**Comment by ermakov-oleg** [comment]
Hi! When is the release planned?
Do you need my help with uploading the package to PyPI or will you and @ods manage it yourselves?

**Comment by chdsbd** [comment]
I'm pushed a new version but I think we need to figure out authentication

**Comment by chdsbd** [comment]
@ods I think since you own squawk-cli, you'd need to either transfer the project, add @sbdchd and myself as collaborators, or configure https://docs.pypi.org/trusted-publishers/adding-a-publisher/ so we can publish via OpenID Connect

**Comment by ods** [comment]
Hi @chdsbd, is [chdsbd](https://pypi.org/user/chdsbd/) the correct user?

**Comment by ods** [comment]
@ermakov-oleg, is [ermakov](https://pypi.org/user/ermakov/) the correct user? I'm planning to also add you as a maintainer, so that you can help with setting it up.

**Comment by chdsbd** [comment]
@ods I use `cdignam` on PyPi

**Comment by ods** [comment]
> @ods I use `cdignam` on PyPi

Added. Feel free removing me after successful publishing.

**Comment by chdsbd** [comment]
I finally got publishing work, so 1.2.0 is on pypi

**Comment by ods** [comment]
Excellent! Is there a change this way of installation being mentioned in the docs?

**Comment by chdsbd** [comment]
Hey @ods, I updated the readme to mention you can install squawk via pip:

https://github.com/sbdchd/squawk/blob/013a414be33981fd458e7c7a284095eedae265f8/README.md#L19-L21

**Pull request merged**
